### ISSUE TITLE
How can I get it running

### ISSUE THREAD

**Issue by scramatte** [Cecchellone/fail2ban-api#1]
Hi,

I need some help to get running.
I'm using debian 12 

TypeError: unsupported operand type(s) for |: 'type' and 'type'

What I've missed?

Does it possible to run as daemon and bind only on 127.0.0.1 ?

Regards

**Comment by Cecchellone** [comment]
Hi!
Which version of Python are you using?
Also, could you let me know which line caused the error?

**Comment by scramatte** [comment]
Hi,

I'm using Python 3.9.2

  File "/home/scramatte/fail2ban-api/./app.py", line 2, in <module>
    from fail2ban import fail2ban
  File "/home/scramatte/fail2ban-api/fail2ban.py", line 30, in <module>
    class fail2ban:
  File "/home/scramatte/fail2ban-api/fail2ban.py", line 125, in fail2ban
    def unban(self, *ip: IPv4Address | IPv6Address):

**Comment by Cecchellone** [comment]
Have you installed the required libraries?  
To do so, run this command in your project directory:  
```bash
pip install -r requirements.txt
```  
I'm assuming you have `pip` installed to manage Python libraries.  
If not, you can follow the instructions on [this page](https://pip.pypa.io/en/stable/installation/).  

I also recommend using a Python virtual environment to install the required libraries. Once you have `pip` installed, you can refer to [this guide](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/) for more details.  

If you'd like to daemonize the application, you should create a proper [systemd unit file](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/using_systemd_unit_files_to_customize_and_optimize_your_system/assembly_working-with-systemd-unit-files_working-with-systemd#ref_important-service-section-options_assembly_working-with-systemd-unit-files) to run it as a service.  

By the way, I'll soon create a Dockerfile for this project, so it can be easily run as a service without manual configuration.

**Comment by scramatte** [comment]
Thank you. Docker will be very nice 
Meanwhile I will test as you told me

Regards

**Comment by scramatte** [comment]
Hi,  dependencies are fine  but I still have the problem

```
#pip install -r requirements.txt
Requirement already satisfied: fastapi in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.63.0)
Requirement already satisfied: uvicorn in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.13.3)
```

```
#python3 app.py 
Traceback (most recent call last):
  File "/home/scramatte/fail2ban-api/app.py", line 2, in <module>
    from fail2ban import fail2ban
  File "/home/scramatte/fail2ban-api/fail2ban.py", line 30, in <module>
    class fail2ban:
  File "/home/scramatte/fail2ban-api/fail2ban.py", line 125, in fail2ban
    def unban(self, *ip: IPv4Address | IPv6Address):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by Cecchellone** [comment]
The problem is with your Python version!
I tested it, and it works with Python 3.11 and newer.
Type coupling isn’t supported until Python 3.10, if I remember correctly.
While dockerizing the app, I tried using Python 3.9 instead of 3.11 and encountered the same error as you.

**Comment by Cecchellone** [comment]
I've uploaded a Docker image to [Docker Hub](https://hub.docker.com/r/cecchellone/fail2ban-api).
Please check if it works now, so I can close the issue.
